#!/bin/sh
echo "Running pre-commit hook"
# Run the formatter
node -e "require('child_process').execSync('yarn format', { stdio: 'inherit' })"
# Stage the formatting changes
git add .
echo "You are ready to push your code :)"